[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "STATUT MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non Essentiels"
newsButton = "ACTUALITÉS"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun serveur sélectionné"
launchDetails = "Veuillez patienter.."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Vérification des actualités.."
newsErrorFailedSpan = "Échec du chargement des actualités"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Aucune actualité"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION MINECRAFT"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "EMAIL OU NOM D'UTILISATEUR"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "mot de passe oublié ?"
loginRememberMeText = "se souvenir de moi ?"
loginButtonText = "CONNEXION"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d’un compte ?"
loginPasswordDisclaimer1 = "Votre mot de passe est envoyé directement à Mojang et n’est jamais stocké."
loginPasswordDisclaimer2 = "{appName} n’est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Se connecter avec Microsoft"
loginWithMojang = "Se connecter avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponibles"
serverSelectConfirm = "Sélectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Sélectionner un compte"
accountSelectConfirm = "Sélectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "À propos"
navUpdates = "Mises à jour"
navDone = "Terminé"
tabAccountHeaderText = "Paramètres du compte"
tabAccountHeaderDesc = "Ajouter de nouveaux comptes ou gérer ceux existants."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Paramètres Minecraft"
minecraftTabHeaderDesc = "Options liées au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en plein écran."
autoConnectTitle = "Connexion automatique au serveur au lancement."
launchDetachedTitle = "Lancer le jeu séparé du launcher."
launchDetachedDesc = "Si le jeu n’est pas séparé, fermer le launcher fermera aussi le jeu."
tabModsHeaderText = "Paramètres des mods"
tabModsHeaderDesc = "Activer ou désactiver les mods."
switchServerButton = "Changer"
requiredMods = "Mods requis"
optionalMods = "Mods optionnels"
dropinMods = "Mods à déposer"
addMods = "Ajouter des mods"
dropinRefreshNote = "(F5 pour actualiser)"
shaderpacks = "Packs de shaders"
shaderpackDesc = "Activer ou désactiver les shaders. Attention, les shaders nécessitent une machine puissante. Vous pouvez ajouter vos packs ici."
selectShaderpack = "Sélectionner un shaderpack"
tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Gérer la configuration de Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "RAM maximale"
minRAM = "RAM minimale"
memoryDesc = "La mémoire minimale recommandée est de 3 Go. Mettre la même valeur pour min et max peut réduire les lags."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Sélectionner l’exécutable Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "L’exécutable Java est validé avant le lancement du jeu."
javaPathDesc = "Le chemin doit se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM supplémentaires"
jvmOptsDesc = "Options à fournir à la JVM au lancement. <em>-Xms</em> et <em>-Xmx</em> ne doivent pas être inclus."
launcherTabHeaderText = "Paramètres du launcher"
launcherTabHeaderDesc = "Options liées au launcher."
allowPrereleaseTitle = "Autoriser les versions préliminaires."
allowPrereleaseDesc = "Les préversions incluent de nouvelles fonctionnalités qui ne sont pas forcément stables.<br>Ceci sera toujours vrai si vous utilisez une préversion."
dataDirectoryTitle = "Dossier de données"
selectDataDirectory = "Sélectionner le dossier de données"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = "Tous les fichiers du jeu et installations locales de Java seront stockés dans ce dossier.<br>Les captures d’écran et sauvegardes sont stockées dans le dossier instance correspondant au serveur."
aboutTabHeaderText = "À propos"
aboutTabHeaderDesc = "Informations et notes de version."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "Console développeur"
releaseNotes = "Notes de version"
changelog = "Changelog"
noReleaseNotes = "Aucune note de version"
viewReleaseNotes = "Voir les notes sur GitHub"
launcherUpdatesHeaderText = "Mises à jour du launcher"
launcherUpdatesHeaderDesc = "Télécharger, installer et consulter les mises à jour."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Nouveautés"
updateReleaseNotes = "Notes de mise à jour"

[ejs.waiting]
waitingText = "En attente de Microsoft.."

[ejs.welcome]
continueButton = "CONTINUER"

[js.discord]
waiting = "En attente du client.."
state = "Serveur : {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "CONNEXION"
loggingIn = "CONNEXION EN COURS"
success = "SUCCÈS"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Valeur invalide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur inconnue lors de la connexion"
desc = "Une erreur inconnue est survenue. Consultez la console pour plus de détails."

[js.landing.launch]
pleaseWait = "Veuillez patienter.."
failureTitle = "Erreur lors du lancement"
failureText = "Voir la console (CTRL + Shift + i) pour plus de détails."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement.."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Analyse du système.."
noCompatibleJava = "Aucune installation Java 64 bits trouvée"
installJavaMessage = "Pour lancer Minecraft, vous avez besoin de Java {major} 64 bits. Voulez-vous que nous l’installions ?"
installJava = "Installer Java"
installJavaManually = "Installer manuellement"
javaDownloadPrepare = "Préparation du téléchargement de Java.."
javaDownloadFailureTitle = "Erreur lors du téléchargement de Java"
javaDownloadFailureText = "Voir la console (CTRL + Shift + i) pour plus de détails."
javaRequired = "Java est requis<br>pour lancer"
javaRequiredMessage = "Une installation valide de Java {major} x64 est requise.<br><br>Consultez notre <a href=\"https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java\">guide Java</a> pour l’installer manuellement."
javaRequiredDismiss = "Je comprends"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Échec de la détection d’une distribution OpenJDK."
javaDownloadCorruptedError = "JDK corrompu, le fichier peut être endommagé."
extractingJava = "Extraction de Java"
javaInstalled = "Java installé !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des infos serveur.."
fatalError = "Erreur fatale"
unableToLoadDistributionIndex = "Impossible de charger l’index de distribution. Voir la console (CTRL + Shift + i)."
pleaseWait = "Veuillez patienter.."
errorDuringLaunchTitle = "Erreur lors du lancement"
errorDuringLaunchText = "Voir la console (CTRL + Shift + i) pour plus de détails."
validatingFileIntegrity = "Validation de l’intégrité des fichiers.."
errorDuringFileVerificationTitle = "Erreur lors de la vérification des fichiers"
downloadingFiles = "Téléchargement des fichiers.."
errorDuringFileDownloadTitle = "Erreur de téléchargement"
preparingToLaunch = "Préparation du lancement.."
launchingGame = "Lancement du jeu.."
launchWrapperNotDownloaded = "Le fichier principal LaunchWrapper n’a pas été téléchargé correctement, le jeu ne peut pas se lancer.<br><br>Désactivez temporairement votre antivirus et relancez.<br><br>Si possible, <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">signalez un bug</a> avec votre antivirus."
doneEnjoyServer = "Terminé. Bon jeu !"
checkConsoleForDetails = "Vérifiez la console (CTRL + Shift + i) pour plus de détails."

[js.landing.news]
checking = "Vérification des actualités"

[js.landing.discord]
loading = "Chargement du jeu.."
joining = "Connexion au serveur !"
joined = "Exploration en cours !"

[js.overlay]
dismiss = "Fermer"

[js.settings.fileSelectors]
executables = "Exécutables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Erreur"
errorMessage = "Échec de l’authentification Microsoft. Réessayez."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Erreur"
errorMessage = "Échec de la déconnexion Microsoft. Réessayez."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Sélectionner un compte"
selectedButton = "Compte sélectionné &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>Ceci est votre dernier compte"
lastAccountWarningMessage = "Pour utiliser le launcher vous devez avoir au moins un compte connecté.<br><br>Êtes-vous sûr de vouloir vous déconnecter ?"
confirmButton = "Je suis sûr"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d’utilisateur"
uuid = "UUID"
selectAccount = "Sélectionner un compte"
selectedAccount = "Compte sélectionné ✓"
logout = "Déconnexion"

[js.settings.dropinMods]
removeButton = "Supprimer"
deleteFailedTitle = "Échec de suppression du mod {fullName}"
deleteFailedMessage = "Vérifiez que le fichier n’est pas utilisé et réessayez."
failedToggleTitle = "Échec de l’activation/désactivation de certains mods"
okButton = "OK"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Sélectionné : Java {version} ({vendor})"
invalidSelection = "Sélection invalide"
requiresJava = "Requiert Java {major} x64."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Préversion"
stableReleaseTitle = "Version stable"
releaseNotesFailed = "Impossible de charger les notes de version."

[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible"
newPreReleaseTitle = "Nouvelle préversion disponible"
downloadingButton = "Téléchargement.."
downloadButton = 'Télécharger depuis GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Fermez le launcher et exécutez le dmg pour mettre à jour.</span>'
latestVersionTitle = "Vous utilisez la dernière version"
checkForUpdatesButton = "Vérifier les mises à jour"
checkingForUpdatesButton = "Vérification des mises à jour.."

[js.settings.msftLogin]
errorTitle = "Connexion Microsoft échouée"
errorMessage = "Impossible d’authentifier votre compte Microsoft. Réessayez."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur fatale : impossible de charger l’index"
fatalErrorMessage = "Impossible d’établir une connexion avec nos serveurs pour télécharger l’index de distribution. Aucun fichier local disponible.<br><br>L’index de distribution est essentiel pour fournir les infos serveur. Vérifiez votre connexion et relancez."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Échec du rafraîchissement de la connexion"
failedMessage = "Impossible de rafraîchir la connexion pour <strong>{account}</strong>. Sélectionnez un autre compte ou reconnectez-vous."
failedMessageSelectAnotherAccount = "Impossible de rafraîchir la connexion pour <strong>{account}</strong>. Veuillez vous reconnecter."
loginButton = "Connexion"
selectAnotherAccountButton = "Sélectionner un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Vérification des mises à jour..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Vérifier les mises à jour"

[js.auth.microsoft.error]
noProfileTitle = "Erreur lors de la connexion :<br>Profil non configuré"
noProfileDesc = "Votre compte Microsoft n’a pas encore de profil Minecraft. Configurez-le sur <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Si vous n’avez pas acheté le jeu, vous pouvez le faire sur <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Erreur :<br>Pas de compte Xbox"
noXboxAccountDesc = "Votre compte Microsoft n’a pas de compte Xbox associé."
xblBannedTitle = "Erreur :<br>Xbox Live indisponible"
xblBannedDesc = "Votre compte est lié à une région où Xbox Live n’est pas disponible ou interdit."
under18Title = "Erreur :<br>Autorisation parentale requise"
under18Desc = "Les comptes mineurs doivent être ajoutés à une famille par un adulte."
unknownTitle = "Erreur inconnue lors de la connexion"
unknownDesc = "Une erreur inconnue est survenue. Voir la console."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erreur interne :<br>Méthode non autorisée"
methodNotAllowedDesc = "Méthode non autorisée. Merci de signaler cette erreur."
notFoundTitle = "Erreur interne :<br>Introuvable"
notFoundDesc = "L’endpoint d’authentification est introuvable. Merci de signaler cette erreur."
accountMigratedTitle = "Erreur :<br>Compte migré"
accountMigratedDesc = "Ce compte a été migré. Connectez-vous avec votre adresse e-mail."
invalidCredentialsTitle = "Erreur :<br>Identifiants invalides"
invalidCredentialsDesc = "L’email ou le mot de passe est incorrect."
tooManyAttemptsTitle = "Erreur :<br>Trop de tentatives"
tooManyAttemptsDesc = "Trop de tentatives récentes. Réessayez plus tard."
invalidTokenTitle = "Erreur :<br>Jeton invalide"
invalidTokenDesc = "Le jeton fourni est invalide."
tokenHasProfileTitle = "Erreur :<br>Profil déjà attribué"
tokenHasProfileDesc = "Le jeton a déjà un profil assigné."
credentialsMissingTitle = "Erreur :<br>Identifiants manquants"
credentialsMissingDesc = "Nom d’utilisateur/mot de passe manquant ou mot de passe trop court."
invalidSaltVersionTitle = "Erreur :<br>Version de sel invalide"
invalidSaltVersionDesc = "Version de sel invalide."
unsupportedMediaTypeTitle = "Erreur interne :<br>Média non supporté"
unsupportedMediaTypeDesc = "Type de média non supporté. Merci de signaler cette erreur."
accountGoneTitle = "Erreur :<br>Compte migré"
accountGoneDesc = "Le compte a été migré vers Microsoft. Connectez-vous avec Microsoft."
unreachableTitle = "Erreur :<br>Serveurs injoignables"
unreachableDesc = "Impossible de contacter les serveurs. Vérifiez votre connexion."
gameNotPurchasedTitle = "Erreur :<br>Jeu non acheté"
gameNotPurchasedDesc = "Ce compte n’a pas acheté Minecraft. Achetez-le sur <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Erreur inconnue"
unknownErrorDesc = "Une erreur inconnue est survenue. Voir la console."
